"""Invitation_Users

Revision ID: 326b894ec98b
Revises: 99ed743aeaa0
Create Date: 2019-02-23 12:24:21.842879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326b894ec98b'
down_revision = '99ed743aeaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['invitation_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitation_names')
    # ### end Alembic commands ###
