"""Add Shared Room Flag

Revision ID: 5ebbc7a9f90f
Revises: d187d1815e46
Create Date: 2020-01-19 16:13:30.304374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression


# revision identifiers, used by Alembic.
revision = '5ebbc7a9f90f'
down_revision = 'd187d1815e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('shared_room', sa.Boolean(), nullable=False, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'shared_room')
    # ### end Alembic commands ###
