"""Add guest type

Revision ID: 84ab841732d1
Revises: f3ca19c993d1
Create Date: 2019-07-05 12:35:23.846363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "84ab841732d1"
down_revision = "f3ca19c993d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        guesttype = postgresql.ENUM('ADULT', 'CHILD', 'BABY', name='guesttype')
        guesttype.create(op.get_bind())
    op.add_column(
        "guests",
        sa.Column(
            "type_",
            sa.Enum("ADULT", "CHILD", "BABY", name="guesttype"),
            nullable=False,
            default="ADULT",
            server_default="ADULT",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guests", schema=None) as batch_op:
        batch_op.drop_column("type_")
    # ### end Alembic commands ###
