"""move plus one from invitation to guest

Revision ID: 908f0b6ec2a2
Revises: 84ab841732d1
Create Date: 2019-07-05 15:59:59.213547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "908f0b6ec2a2"
down_revision = "84ab841732d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guests",
        sa.Column(
            "plus_one", sa.Boolean(), nullable=False, default=False, server_default="0",
        ),
    )
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.drop_column("plus_one")
        batch_op.drop_column("plus_one_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation", sa.Column("plus_one_name", sa.VARCHAR(length=256), nullable=True)
    )
    op.add_column("invitation", sa.Column("plus_one", sa.BOOLEAN(), nullable=False))
    with op.batch_alter_table("guests", schema=None) as batch_op:
        batch_op.drop_column("plus_one")
    # ### end Alembic commands ###
