"""Add Password Recovery

Revision ID: 99ed743aeaa0
Revises: a503d83d34c7
Create Date: 2019-02-05 17:07:43.230523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99ed743aeaa0"
down_revision = "a503d83d34c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("password_recovery_code", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "user", sa.Column("password_recovery_gendate", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_recovery_gendate")
    op.drop_column("user", "password_recovery_code")
    # ### end Alembic commands ###
