"""Add Menu Options

Revision ID: 9b7283618a15
Revises: ba2d26e74d6b
Create Date: 2019-03-31 19:52:05.958286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b7283618a15"
down_revision = "ba2d26e74d6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "course",
            sa.Enum("STARTER", "MAIN", "DESERT", name="menucourse"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("vegetarian", sa.Boolean(), nullable=False),
        sa.Column("gluten_free", sa.Boolean(), nullable=False),
        sa.Column("additional_info", sa.String(length=256)),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guest_choices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=True),
        sa.Column("starter_id", sa.Integer(), nullable=True),
        sa.Column("main_id", sa.Integer(), nullable=True),
        sa.Column("desert_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["desert_id"], ["menu_items.id"]),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.id"]),
        sa.ForeignKeyConstraint(["main_id"], ["menu_items.id"]),
        sa.ForeignKeyConstraint(["starter_id"], ["menu_items.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guest_choices")
    op.drop_table("menu_items")
    # ### end Alembic commands ###
