"""Adding guest details

Revision ID: a1164d0428ba
Revises: 9b7283618a15
Create Date: 2019-06-16 13:47:09.475151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1164d0428ba"
down_revision = "9b7283618a15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conventions = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
    with op.batch_alter_table("guests", naming_convention=conventions) as batch_op:
        batch_op.add_column(sa.Column("is_coming", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("desert_course", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("first_course", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("main_course", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_guests_desert_course_menu_items",
            "menu_items",
            ["desert_course"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_guests_first_course_menu_items", "menu_items", ["first_course"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_guests_main_course_menu_items", "menu_items", ["main_course"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conventions = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
    with op.batch_alter_table("guests", naming_convention=conventions) as batch_op:
        batch_op.drop_constraint(
            "fk_guests_first_course_menu_items", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_guests_main_course_menu_items", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_guests_desert_course_menu_items", type_="foreignkey"
        )
        batch_op.drop_column("main_course")
        batch_op.drop_column("first_course")
        batch_op.drop_column("desert_course")
        batch_op.drop_column("is_coming")
