"""Adding Email verification

Revision ID: a503d83d34c7
Revises: c3befb2c9f73
Create Date: 2019-01-18 17:19:59.587957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a503d83d34c7"
down_revision = "c3befb2c9f73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("verification_code", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("verified_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verified_on")
    op.drop_column("user", "verified")
    op.drop_column("user", "verification_code")
    # ### end Alembic commands ###
