"""Remove Relationship between user and invitation_group

Revision ID: ba2d26e74d6b
Revises: f2c307c22f21
Create Date: 2019-03-07 14:13:36.269910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba2d26e74d6b"
down_revision = "f2c307c22f21"
branch_labels = None
depends_on = None


def upgrade():
    conventions = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", naming_convention=conventions) as batch_op:
        batch_op.drop_constraint(
            "fk_users_invitation_group_id_invitation_group", type_="foreignkey"
        )
        batch_op.drop_column("invitation_group_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("invitation_group_id", sa.INTEGER(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "invitation_group", ["invitation_group_id"], ["id"]
        )

    # ### end Alembic commands ###
