"""add arriving dates

Revision ID: d187d1815e46
Revises: 908f0b6ec2a2
Create Date: 2019-11-16 11:21:52.090177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d187d1815e46"
down_revision = "908f0b6ec2a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation", sa.Column("arriving", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "invitation", sa.Column("leaving", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitation", "leaving")
    op.drop_column("invitation", "arriving")
    # ### end Alembic commands ###
