"""Add IG Payment

Revision ID: deb5a752f071
Revises: 5ebbc7a9f90f
Create Date: 2020-05-30 17:24:10.583629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "deb5a752f071"
down_revision = "5ebbc7a9f90f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation") as batch_op:
        batch_op.add_column(sa.Column("paid", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("room_cost", sa.Numeric(precision=7, scale=2), nullable=True),
        )
        batch_op.add_column(sa.Column("room_number", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitation") as batch_op:
        batch_op.drop_column("room_number")
        batch_op.drop_column("room_cost")
        batch_op.drop_column("paid")
    # ### end Alembic commands ###
