"""staying_in_house option

Revision ID: f3ca19c993d1
Revises: a1164d0428ba
Create Date: 2019-06-16 18:55:02.689488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3ca19c993d1"
down_revision = "a1164d0428ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation", sa.Column("staying_in_house", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invitation", "staying_in_house")
    # ### end Alembic commands ###
