name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to push (e.g., v1.2.3)"
        required: true
        type: string

jobs:
  dependency_review:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependency Review (fail on HIGH/CRITICAL)
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          # Provide refs since this is not a PR workflow
          base-ref: ${{ github.event.repository.default_branch }}
          head-ref: ${{ github.sha }}

  release:
    name: Scan and Tag
    runs-on: ubuntu-latest
    needs: dependency_review
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        if: success()
        run: |
          set -euo pipefail
          TAG="${{ github.event.inputs.tag }}"
          if [ -z "$TAG" ]; then
            echo "::error::Input 'tag' is empty."
            exit 1
          fi
          echo "Preparing to push tag: $TAG"
          if git ls-remote --tags origin "refs/tags/$TAG" | grep -q "$TAG"; then
            echo "Tag $TAG already exists on origin. Skipping."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
